apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bl-ns-res-prj  
  namespace: argocd
spec:
  description: project description
  sourceRepos:
    - “*”
  destinations:
    - server: https://kubernetes.default.svc
      namespace: “ns-1“
  clusterResourceWhitelist:
    - group: “”
      kind: “Namespace“
  namespaceResourceBlacklist: # Allow all namespaced-scoped resources to be created, except for NetworkPolicy
    - group: “”
      kind: “NetworkPolicy"
