apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: guestbook
    server: "https://kubernetes.default.svc"
  project: demo-project
  source:
   path: helm-sampleapp
   repoURL: "https://github.com/lerndevops/argocd.git"
   targetRevision: HEAD
