apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-directory
  namespace: argocd
  labels:
    app.kubernetes.io/name: root-app-directory
  #finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: 07-app-of-apps/directory-of-apps
    repoURL: https://github.com/lerndevops/argocd.git
    targetRevision: main
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: false
    syncOptions:
    - allowEmpty=true
    - CreateNamespace=true
  ignoreDifferences:
   - kind: Application
     group: argoproj.io
     jsonPointers:
      - /status
     


